# -*- coding: utf-8 -*-
"""Basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gwpc9yBjDjTySaV6jFVstLR9RJ03IFHV

# Variables and Data
"""

print("Yasiru")

name = input("Enter your name :- ")
print("Hello ", name)

name = input("Enter your name :- ")
age = int(input("Enter your age :- "))
print("Hiii " ,name, " you will be ",age + 1 ," next year !")

a = 7
b=3
print("Add:", a + b)            # 10
print("Subtract:", a - b)       # 4
print("Multiply:", a * b)       # 21
print("Divide:", a / b)         # 2.3333
print("Floor Divide:", a // b)  # 2
print("Modulus:", a % b)        # 1
print("Power:", a ** b)         # 343 (7 x 7 x 7)

"""# Control Structure

## Decision making
"""

score = int(input("Enter your score: "))

if score >= 90:
    print("Grade: A")
elif score >= 75:
    print("Grade: B")
elif score >= 60:
    print("Grade: C")
else:
    print("Grade: F")

for i in range(5):
  if i==3:
    continue
  print(i)

count = 0
while count < 3:
    print("Count is", count)
    count += 1

"""## Logical Operators"""

age = 25
is_student = True

if age > 18 and is_student:
    print("Eligible for student discount")

# Example using 'not' operator
is_raining = False

if not is_raining:
    print("It's not raining")

# Example using 'or' operator
temperature = 25
is_hot = temperature > 30
is_sunny = True

if is_hot or is_sunny:
    print("It's either hot or sunny (or both)")

"""# For Loop"""

names = ["yasiru", "nadeesha", "amal"]
for name in names:
  print(name)

for i in range(1,6):
  print(i)

for i in range(3):
  for j in range(2):
    print(j)

"""# While Loop"""

count = 5
while count > 0:
    print("Countdown:", count)
    count -= 1
print("Go!")

"""# Loop Control(break , continue)"""

nums = [1, 3, 5, 6, 7, 9]
for num in nums:
    if num % 2 == 0:
        print("Found even:", num)
        break

for i in range(5):
    if i == 3:
        continue
    print(i)